from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from aliaroaccessoryboards.switch_config import Relay, Topology, InitialState, Connection, MuxItem


class TestBus(Enum):
    POSITIVE = 1
    NEGATIVE = -1


@dataclass
class ChannelDefinition:
    channel: int
    is_source: bool = False


topology = Topology(
    relays=[
        Relay("CH01_NEG", 0), Relay("CH01_POS", 1), Relay("CH02_NEG", 2), Relay("CH02_POS", 3),
        Relay("CH03_NEG", 4), Relay("CH03_POS", 5), Relay("CH04_NEG", 6), Relay("CH04_POS", 7),
        Relay("CH05_NEG", 8), Relay("CH05_POS", 9), Relay("CH06_NEG", 10), Relay("CH06_POS", 11),
        Relay("CH07_NEG", 12), Relay("CH07_POS", 13), Relay("CH08_NEG", 14), Relay("CH08_POS", 15),
        Relay("CH09_NEG", 16), Relay("CH09_POS", 17), Relay("CH10_NEG", 18), Relay("CH10_POS", 19),
        Relay("CH11_NEG", 20), Relay("CH11_POS", 21), Relay("CH12_NEG", 22), Relay("CH12_POS", 23),
        Relay("CH13_NEG", 24), Relay("CH13_POS", 25), Relay("CH14_NEG", 26), Relay("CH14_POS", 27),
        Relay("CH15_NEG", 28), Relay("CH15_POS", 29), Relay("CH16_NEG", 30), Relay("CH16_POS", 31),
        Relay("CH17_NEG", 32), Relay("CH17_POS", 33), Relay("CH18_NEG", 34), Relay("CH18_POS", 35),
        Relay("CH19_NEG", 36), Relay("CH19_POS", 37), Relay("CH20_NEG", 38), Relay("CH20_POS", 39),
        Relay("CH21_NEG", 40), Relay("CH21_POS", 41), Relay("CH22_NEG", 42), Relay("CH22_POS", 43),
        Relay("CH23_NEG", 44), Relay("CH23_POS", 45), Relay("CH24_NEG", 46), Relay("CH24_POS", 47),
        Relay("CH25_NEG", 48), Relay("CH25_POS", 49), Relay("CH26_NEG", 50), Relay("CH26_POS", 51),
        Relay("CH27_NEG", 52), Relay("CH27_POS", 53), Relay("CH28_NEG", 54), Relay("CH28_POS", 55),
        Relay("CH29_NEG", 56), Relay("CH29_POS", 57), Relay("CH30_NEG", 58), Relay("CH30_POS", 59),
        Relay("CH31_NEG", 60), Relay("CH31_POS", 61), Relay("CH32_NEG", 62), Relay("CH32_POS", 63),
        Relay("GND_NEG", 64), Relay("GND_POS", 65), Relay("OUT01_NEG", 66), Relay("OUT01_POS", 67),
        Relay("OUT02_NEG", 68), Relay("OUT02_POS", 69), Relay("OUT03_NEG", 70), Relay("OUT03_POS", 71),
        Relay("OUT04_NEG", 72), Relay("OUT04_POS", 73), Relay("OUT05_NEG", 74), Relay("OUT05_POS", 75),
    ],
    initial_state=InitialState(
        open=[
            "CH01_NEG", "CH01_POS", "CH02_NEG", "CH02_POS", "CH03_NEG", "CH03_POS", "CH04_NEG", "CH04_POS",
            "CH05_NEG", "CH05_POS", "CH06_NEG", "CH06_POS", "CH07_NEG", "CH07_POS", "CH08_NEG", "CH08_POS",
            "CH09_NEG", "CH09_POS", "CH10_NEG", "CH10_POS", "CH11_NEG", "CH11_POS", "CH12_NEG", "CH12_POS",
            "CH13_NEG", "CH13_POS", "CH14_NEG", "CH14_POS", "CH15_NEG", "CH15_POS", "CH16_NEG", "CH16_POS",
            "CH17_NEG", "CH17_POS", "CH18_NEG", "CH18_POS", "CH19_NEG", "CH19_POS", "CH20_NEG", "CH20_POS",
            "CH21_NEG", "CH21_POS", "CH22_NEG", "CH22_POS", "CH23_NEG", "CH23_POS", "CH24_NEG", "CH24_POS",
            "CH25_NEG", "CH25_POS", "CH26_NEG", "CH26_POS", "CH27_NEG", "CH27_POS", "CH28_NEG", "CH28_POS",
            "CH29_NEG", "CH29_POS", "CH30_NEG", "CH30_POS", "CH31_NEG", "CH31_POS", "CH32_NEG", "CH32_POS",
            "GND_NEG", "GND_POS", "OUT01_NEG", "OUT01_POS", "OUT02_NEG", "OUT02_POS", "OUT03_NEG", "OUT03_POS",
            "OUT04_NEG", "OUT04_POS", "OUT05_NEG", "OUT05_POS"
        ]),
    channel_list=[
        "DUT_GND""DUT_CH1", "DUT_CH2", "DUT_CH3", "DUT_CH4", "DUT_CH5", "DUT_CH6", "DUT_CH7", "DUT_CH8", "DUT_CH9",
        "DUT_CH10,""DUT_CH11", "DUT_CH12", "DUT_CH13", "DUT_CH14", "DUT_CH15", "DUT_CH16", "DUT_CH17", "DUT_CH18",
        "DUT_CH19", "DUT_CH20", "DUT_CH21", "DUT_CH22", "DUT_CH23", "DUT_CH24", "DUT_CH25", "DUT_CH26", "DUT_CH27",
        "DUT_CH28", "DUT_CH29", "DUT_CH30", "DUT_CH31", "DUT_CH32", "J4_CENTER,""J4_SHIELD", "J5_CENTER", "J5_SHIELD",
        "J6_CENTER", "J6_SHIELD", "J7_CENTER", "J7_SHIELD", "J8", "J9", "BUS_POS", "BUS_NEG"
    ],
    connection_list=[
        Connection(src="DUT_GND", dest="BUS_POS", relays=["RELAY_GND_POS"]),
        Connection(src="DUT_GND", dest="BUS_NEG", relays=["RELAY_GND_NEG"]),
        Connection(src="DUT_CH1", dest="BUS_POS", relays=["RELAY_CH1_POS"]),
        Connection(src="DUT_CH1", dest="BUS_NEG", relays=["RELAY_CH1_NEG"]),
        Connection(src="DUT_CH2", dest="BUS_POS", relays=["RELAY_CH2_POS"]),
        Connection(src="DUT_CH2", dest="BUS_NEG", relays=["RELAY_CH2_NEG"]),
        Connection(src="DUT_CH3", dest="BUS_POS", relays=["RELAY_CH3_POS"]),
        Connection(src="DUT_CH3", dest="BUS_NEG", relays=["RELAY_CH3_NEG"]),
        Connection(src="DUT_CH4", dest="BUS_POS", relays=["RELAY_CH4_POS"]),
        Connection(src="DUT_CH4", dest="BUS_NEG", relays=["RELAY_CH4_NEG"]),
        Connection(src="DUT_CH5", dest="BUS_POS", relays=["RELAY_CH5_POS"]),
        Connection(src="DUT_CH5", dest="BUS_NEG", relays=["RELAY_CH5_NEG"]),
        Connection(src="DUT_CH6", dest="BUS_POS", relays=["RELAY_CH6_POS"]),
        Connection(src="DUT_CH6", dest="BUS_NEG", relays=["RELAY_CH6_NEG"]),
        Connection(src="DUT_CH7", dest="BUS_POS", relays=["RELAY_CH7_POS"]),
        Connection(src="DUT_CH7", dest="BUS_NEG", relays=["RELAY_CH7_NEG"]),
        Connection(src="DUT_CH8", dest="BUS_POS", relays=["RELAY_CH8_POS"]),
        Connection(src="DUT_CH8", dest="BUS_NEG", relays=["RELAY_CH8_NEG"]),
        Connection(src="DUT_CH9", dest="BUS_POS", relays=["RELAY_CH9_POS"]),
        Connection(src="DUT_CH9", dest="BUS_NEG", relays=["RELAY_CH9_NEG"]),
        Connection(src="DUT_CH10", dest="BUS_POS", relays=["RELAY_CH10_POS"]),
        Connection(src="DUT_CH10", dest="BUS_NEG", relays=["RELAY_CH10_NEG"]),
        Connection(src="DUT_CH11", dest="BUS_POS", relays=["RELAY_CH11_POS"]),
        Connection(src="DUT_CH11", dest="BUS_NEG", relays=["RELAY_CH11_NEG"]),
        Connection(src="DUT_CH12", dest="BUS_POS", relays=["RELAY_CH12_POS"]),
        Connection(src="DUT_CH12", dest="BUS_NEG", relays=["RELAY_CH12_NEG"]),
        Connection(src="DUT_CH13", dest="BUS_POS", relays=["RELAY_CH13_POS"]),
        Connection(src="DUT_CH13", dest="BUS_NEG", relays=["RELAY_CH13_NEG"]),
        Connection(src="DUT_CH14", dest="BUS_POS", relays=["RELAY_CH14_POS"]),
        Connection(src="DUT_CH14", dest="BUS_NEG", relays=["RELAY_CH14_NEG"]),
        Connection(src="DUT_CH15", dest="BUS_POS", relays=["RELAY_CH15_POS"]),
        Connection(src="DUT_CH15", dest="BUS_NEG", relays=["RELAY_CH15_NEG"]),
        Connection(src="DUT_CH16", dest="BUS_POS", relays=["RELAY_CH16_POS"]),
        Connection(src="DUT_CH16", dest="BUS_NEG", relays=["RELAY_CH16_NEG"]),
        Connection(src="DUT_CH17", dest="BUS_POS", relays=["RELAY_CH17_POS"]),
        Connection(src="DUT_CH17", dest="BUS_NEG", relays=["RELAY_CH17_NEG"]),
        Connection(src="DUT_CH18", dest="BUS_POS", relays=["RELAY_CH18_POS"]),
        Connection(src="DUT_CH18", dest="BUS_NEG", relays=["RELAY_CH18_NEG"]),
        Connection(src="DUT_CH19", dest="BUS_POS", relays=["RELAY_CH19_POS"]),
        Connection(src="DUT_CH19", dest="BUS_NEG", relays=["RELAY_CH19_NEG"]),
        Connection(src="DUT_CH20", dest="BUS_POS", relays=["RELAY_CH20_POS"]),
        Connection(src="DUT_CH20", dest="BUS_NEG", relays=["RELAY_CH20_NEG"]),
        Connection(src="DUT_CH21", dest="BUS_POS", relays=["RELAY_CH21_POS"]),
        Connection(src="DUT_CH21", dest="BUS_NEG", relays=["RELAY_CH21_NEG"]),
        Connection(src="DUT_CH22", dest="BUS_POS", relays=["RELAY_CH22_POS"]),
        Connection(src="DUT_CH22", dest="BUS_NEG", relays=["RELAY_CH22_NEG"]),
        Connection(src="DUT_CH23", dest="BUS_POS", relays=["RELAY_CH23_POS"]),
        Connection(src="DUT_CH23", dest="BUS_NEG", relays=["RELAY_CH23_NEG"]),
        Connection(src="DUT_CH24", dest="BUS_POS", relays=["RELAY_CH24_POS"]),
        Connection(src="DUT_CH24", dest="BUS_NEG", relays=["RELAY_CH24_NEG"]),
        Connection(src="DUT_CH25", dest="BUS_POS", relays=["RELAY_CH25_POS"]),
        Connection(src="DUT_CH25", dest="BUS_NEG", relays=["RELAY_CH25_NEG"]),
        Connection(src="DUT_CH26", dest="BUS_POS", relays=["RELAY_CH26_POS"]),
        Connection(src="DUT_CH26", dest="BUS_NEG", relays=["RELAY_CH26_NEG"]),
        Connection(src="DUT_CH27", dest="BUS_POS", relays=["RELAY_CH27_POS"]),
        Connection(src="DUT_CH27", dest="BUS_NEG", relays=["RELAY_CH27_NEG"]),
        Connection(src="DUT_CH28", dest="BUS_POS", relays=["RELAY_CH28_POS"]),
        Connection(src="DUT_CH28", dest="BUS_NEG", relays=["RELAY_CH28_NEG"]),
        Connection(src="DUT_CH29", dest="BUS_POS", relays=["RELAY_CH29_POS"]),
        Connection(src="DUT_CH29", dest="BUS_NEG", relays=["RELAY_CH29_NEG"]),
        Connection(src="DUT_CH30", dest="BUS_POS", relays=["RELAY_CH30_POS"]),
        Connection(src="DUT_CH30", dest="BUS_NEG", relays=["RELAY_CH30_NEG"]),
        Connection(src="DUT_CH31", dest="BUS_POS", relays=["RELAY_CH31_POS"]),
        Connection(src="DUT_CH31", dest="BUS_NEG", relays=["RELAY_CH31_NEG"]),
        Connection(src="DUT_CH32", dest="BUS_POS", relays=["RELAY_CH32_POS"]),
        Connection(src="DUT_CH32", dest="BUS_NEG", relays=["RELAY_CH32_NEG"]),
        Connection(src="J4_CENTER", dest="BUS_POS", relays=["RELAY_OUT1_POS"]),
        Connection(src="J4_SHIELD", dest="BUS_NEG", relays=["RELAY_OUT1_NEG"]),
        Connection(src="J5_CENTER", dest="BUS_POS", relays=["RELAY_OUT2_POS"]),
        Connection(src="J5_SHIELD", dest="BUS_NEG", relays=["RELAY_OUT2_NEG"]),
        Connection(src="J6_CENTER", dest="BUS_POS", relays=["RELAY_OUT3_POS"]),
        Connection(src="J6_SHIELD", dest="BUS_NEG", relays=["RELAY_OUT3_NEG"]),
        Connection(src="J7_CENTER", dest="BUS_POS", relays=["RELAY_OUT4_POS"]),
        Connection(src="J7_SHIELD", dest="BUS_NEG", relays=["RELAY_OUT4_NEG"]),
        Connection(src="J8", dest="BUS_POS", relays=["RELAY_OUT5_POS"]),
        Connection(src="J9", dest="BUS_NEG", relays=["RELAY_OUT5_NEG"]),
    ],
    mux_list=[
        MuxItem(src='DUT_GND', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH1', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH2', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH3', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH4', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH5', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH6', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH7', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH8', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH9', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH10', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH11', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH12', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH13', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH14', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH15', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH16', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH17', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH18', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH19', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH20', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH21', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH22', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH23', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH24', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH25', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH26', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH27', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH28', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH29', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH30', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH31', dest=["BUS_POS", "BUS_NEG"]),
        MuxItem(src='DUT_CH32', dest=["BUS_POS", "BUS_NEG"]),
    ]
)
